const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {BrowserWindow,app}=require('electron');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
module.exports=async function verify({service,openSettings,getSettings,largeTrayMenu,getTray}){
  fs.mkdirSync(path.join(__dirname,'../qa-output'),{recursive:true});
  const errors=[];
  const pet=()=>BrowserWindow.getAllWindows().find(w=>w!==getSettings());
  const request=async(route,body)=>{const r=await fetch(service.base+route,{method:body?'PUT':'GET',body:body?JSON.stringify(body):undefined});return r.json();};
  try{
    service.client.start=async()=>{throw new Error('Codex must not start during independent UI test');};
    await sleep(700);
    assert.ok(!getSettings(),'normal startup must not open Settings');
    for(const args of [[],['--settings']]){
      app.emit('second-instance',{},[process.execPath,...args]);await sleep(100);
      assert.ok(!getSettings(),'normal and legacy shortcuts must not open Settings on a second launch');
    }
    app.emit('second-instance',{},[process.execPath,'--open-settings']);
    const settings=getSettings();assert.ok(settings,'explicit settings entry remains available');settings.webContents.on('console-message',(_event,_level,message)=>{if(/Uncaught/.test(message))errors.push(message);});
    await sleep(3000);
    const electronShell=require('electron').shell,originalOpen=electronShell.openExternal,opened=[];
    try{
      electronShell.openExternal=async url=>{opened.push(url);};
      await largeTrayMenu.getItems().find(item=>item.label==='关于 pet-with-you').click();
      assert.deepEqual(opened,[require('../project.cjs').REPOSITORY_URL]);
    }finally{electronShell.openExternal=originalOpen;}
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#petShortcutPreviewHint').hidden`),true);
    assert.match(await settings.webContents.executeJavaScript(`document.querySelector('#clientLauncherResult').textContent`),/尚未创建/);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#followClientStart')===null`),true);
    console.error('VERIFY_STAGE: pet-shortcut-verify.cjs');
    await require('./pet-shortcut-verify.cjs')(settings);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#settingsFileSection').nextElementSibling.tagName`),'FOOTER');
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#locateSettingsFile').textContent.includes('定位')`),true);
    await settings.webContents.executeJavaScript(`document.querySelector('#quotaSeconds').value='17';document.querySelector('#quotaSeconds').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#locateSettingsFile').click();`);
    for(let i=0;i<50;i++){if((await request('/preferences')).quotaSeconds===17)break;await sleep(100);}
    assert.equal((await request('/preferences')).quotaSeconds,17,'locate button flushes settings without waiting on itself');
    if(process.platform==='win32'){
      const handle=settings.getNativeWindowHandle().readBigUInt64LE().toString();
      const iconFile=path.join(__dirname,'..','qa-output','settings-native-icon.png');
      const command=`Add-Type -AssemblyName System.Drawing; Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public class PetIconCheck{[DllImport("user32.dll")] public static extern IntPtr SendMessage(IntPtr h,uint m,IntPtr w,IntPtr l);}'; $h=[PetIconCheck]::SendMessage([IntPtr]${handle},127,[IntPtr]1,[IntPtr]::Zero);if($h -eq [IntPtr]::Zero){throw 'Missing native window icon'};$icon=[Drawing.Icon]::FromHandle($h);$bitmap=$icon.ToBitmap();$bitmap.Save('${iconFile.replaceAll("'","''")}',[Drawing.Imaging.ImageFormat]::Png);$bitmap.Dispose()`;
      await require('node:util').promisify(require('node:child_process').execFile)('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{windowsHide:true,timeout:10000});
    }
    await settings.webContents.executeJavaScript(`document.querySelector('#followClientClose').checked=true;document.querySelector('#followClientClose').dispatchEvent(new Event('change',{bubbles:true}));`);
    await sleep(200);assert.equal((await request('/preferences')).followClientClose,true);
    await settings.webContents.executeJavaScript(`document.querySelector('#followClientClose').checked=false;document.querySelector('#followClientClose').dispatchEvent(new Event('change',{bubbles:true}));`);
    await sleep(200);assert.equal((await request('/preferences')).followClientClose,false);
    for(const window of [settings,pet()]){
      const original=window.webContents.getURL(),count=BrowserWindow.getAllWindows().length;
      assert.equal(window.webContents.getLastWebPreferences().sandbox,true);
      await window.webContents.executeJavaScript(`window.open('about:blank'); location.assign(${JSON.stringify(service.base+'/blocked-navigation-check')}); undefined;`);
      await sleep(150);
      assert.equal(window.webContents.getURL(),original,'app windows reject page-initiated navigation');
      assert.equal(BrowserWindow.getAllWindows().length,count,'app windows reject new renderer windows');
    }
    const order=await settings.webContents.executeJavaScript(`(async()=>{const section=document.querySelector('#apiSection');await moveModule(section,-1);return modules(document.querySelector('#basicPanel')).map(e=>e.id);})()`);
    assert.deepEqual((await request('/preferences')).moduleOrder.basic,order);
    await settings.webContents.executeJavaScript(`moduleOrderLoaded=false;loadModuleOrder(${JSON.stringify({basic:[],gpt:[]})})`);
    console.error('VERIFY_STAGE: module-sort-verify.cjs');
    await require('./module-sort-verify.cjs')(settings,service);
    const sizeControls=await settings.webContents.executeJavaScript(`(()=>{const slider=document.querySelector('.pet-size input[type=range]'),number=document.querySelector('.pet-size input[type=number]'),old=main.pets[0].size;slider.value=555;slider.dispatchEvent(new Event('input'));const fromSlider=Number(number.value)===555&&main.pets[0].size===555;number.value=420;number.dispatchEvent(new Event('input'));const fromNumber=Number(slider.value)===420&&main.pets[0].size===420;number.value=old;number.dispatchEvent(new Event('input'));return {fromSlider,fromNumber};})()`);
    assert.deepEqual(sizeControls,{fromSlider:true,fromNumber:true});
    assert.equal(await pet().webContents.executeJavaScript('window.__dshPetDebug.configOk'),true);
    const config=await request('/config');config.main.animationWeights.move=0;
    await request('/config',config.main);await sleep(600);
    console.error('VERIFY_STAGE: menu-frame-verify.cjs');
    await require('./menu-frame-verify.cjs')(pet());
    console.error('VERIFY_STAGE: interaction-options-verify.cjs');
    await require('./interaction-options-verify.cjs')({pet:pet(),settings,service});
    console.error('VERIFY_STAGE: pet-size-verify.cjs');
    await require('./pet-size-verify.cjs')({pet:pet(),settings,service});
    const drag=await pet().webContents.executeJavaScript(`(async()=>{const s=sprites[0];s.stopMove();s.stopThrow();s.sendBounds(400,300);s.onPointerDown({button:0,pointerId:17,screenX:600,screenY:500,clientX:100,clientY:100});const before={...s.pos};s.onPointerMove({screenX:720,screenY:560});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const result={dx:s.pos.x-before.x,dy:s.pos.y-before.y,wantX:toLocal(120),wantY:toLocal(60),dragAnimation:s.animations.drag.includes(s.anim)};s.dragTrail=[];s.onPointerUp({screenX:720,screenY:560});s.stopThrow();s.stopMove();return result;})()`);
    assert.ok(Math.abs(drag.dx-drag.wantX)<1&&Math.abs(drag.dy-drag.wantY)<1);assert.equal(drag.dragAnimation,true);
    await settings.webContents.executeJavaScript(`(async()=>{document.querySelector('#proxyEndpoint').value='https://quota.example.test/balance';document.querySelector('#credential').value='manual';document.querySelector('#valuePath').value='data.balance';document.querySelector('#proxyKey').value='preview-private-key';await document.querySelector('#saveProxy').onclick();})()`);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#proxyKeyPreview').textContent`),'已保存密钥：preview…');
    await settings.webContents.executeJavaScript(`api('/quota/settings').then(fillQuota)`);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#proxyEndpoint').value`),'https://quota.example.test/balance');
    await settings.webContents.executeJavaScript(`document.querySelector('#proxyProfileName').value='Daily query';document.querySelector('#saveProxyProfile').onclick()`);
    assert.match(await settings.webContents.executeJavaScript(`document.querySelector('#proxyProfileSummary').textContent`),/quota.example.test.*手动密钥/);
    await settings.webContents.executeJavaScript(`document.querySelector('#clearProxy').onclick()`);
    assert.equal((await request('/quota/profiles')).length,1);
    await settings.webContents.executeJavaScript(`document.querySelector('#loadProxyProfile').onclick()`);
    assert.equal((await request('/quota/settings')).proxy.keyPreview,'preview…');
    await settings.webContents.executeJavaScript(`(async()=>{await document.querySelector('#deleteProxyProfile').onclick();await document.querySelector('#clearProxy').onclick();})()`);
    assert.equal((await request('/quota/profiles')).length,0);
    assert.equal((await request('/quota/settings')).proxy,null);
    await settings.webContents.executeJavaScript(`(async()=>{document.querySelector('#apiBaseUrl').value='https://example.test/v1';document.querySelector('#apiModel').value='fixture';document.querySelector('#apiKey').value='private-fixture-key';document.querySelector('#apiProfileName').value='Daily';await document.querySelector('#saveApiProfile').onclick();await document.querySelector('#clearApi').onclick();})()`);
    assert.equal((await request('/api/settings')).configured,false);
    assert.equal((await request('/api/profiles')).length,1);
    assert.match(await settings.webContents.executeJavaScript(`document.querySelector('#apiProfileSummary').textContent`),/example.test.*fixture/);
    await settings.webContents.executeJavaScript(`document.querySelector('#loadApiProfile').onclick()`);
    assert.equal((await request('/api/settings')).configured,true);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#apiKey').value`),'********');
    await settings.webContents.executeJavaScript(`document.querySelector('#saveApi').onclick()`);
    assert.equal(service.apiSettings.key(),'private-fixture-key');
    await settings.webContents.executeJavaScript(`(async()=>{await document.querySelector('#deleteApiProfile').onclick();await document.querySelector('#clearApi').onclick();})()`);
    assert.equal((await request('/api/profiles')).length,0);
    assert.equal((await request('/api/settings')).baseUrl,'');
    // Keep autonomous animations from moving the subject during the mode/position checks.
    await request('/preferences',{disableRoaming:true});
    await sleep(900);
    const stored=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.stopMove();s.stopThrow();s.sendBounds(430,310);return s.pos;})()`);
    await sleep(80);
    const getMode=()=>settings.webContents.executeJavaScript(`({mode:currentMode,clientVisible:!document.querySelector('#gptTab').hidden,api:!!document.querySelector('#apiBaseUrl'),startup:!!document.querySelector('#autostart'),whisperVisible:getComputedStyle([...document.querySelectorAll('#autoWhisperPets label')].find(e=>e.textContent.includes('自动碎碎念'))).display!=='none'})`);
    assert.deepEqual(await getMode(),{mode:'pet',clientVisible:false,api:true,startup:true,whisperVisible:true});
    await settings.webContents.executeJavaScript(`document.querySelector('#connectedMode').checked=true;changeMode()`);await sleep(900);
    assert.equal((await getMode()).clientVisible,true);
    assert.equal(await settings.webContents.executeJavaScript(`currentTab==='gpt'&&!document.querySelector('#gptPanel').hidden&&document.querySelector('#basicPanel').hidden`),true);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#sourceDialog').open`),true);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#clientLauncherDialog').open`),false);
    await settings.webContents.executeJavaScript(`document.querySelector('#chooseApiSource').onclick()`);await sleep(900);
    assert.equal((await request('/preferences')).chatSource,'api');
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#sourceDialog').open`),false);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#clientLauncherDialog').open`),true);
    settings.show();settings.webContents.invalidate();await sleep(250);
    fs.writeFileSync(path.resolve(__dirname,'../qa-output/codex-withu-prompt.png'),(await settings.webContents.capturePage().catch(error=>{throw new Error('Joint prompt capture: '+error.message);})).toPNG());
    await settings.webContents.executeJavaScript(`document.querySelector('#skipClientLauncher').click()`);await sleep(250);
    assert.equal((await request('/client-launcher')).prompted,true);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#clientLauncherDialog').open`),false);
    const tabs=await settings.webContents.executeJavaScript(`(()=>{document.querySelector('#apiBaseUrl').value='https://draft.example/v1';selectTab('gpt');const nested=['createClientLauncher','followClientClose','chatSource','notify','queryAccount','clientPets'].every(id=>document.querySelector('#gptPanel').contains(document.getElementById(id)));selectTab('basic');return {nested,draft:document.querySelector('#apiBaseUrl').value};})()`);
    console.error('VERIFY_STAGE: connection-ui-verify.cjs');
    await require('./connection-ui-verify.cjs')(settings);
    assert.deepEqual(tabs,{nested:true,draft:'https://draft.example/v1'});
    assert.deepEqual(await pet().webContents.executeJavaScript('sprites[0].pos'),stored);
    await settings.webContents.executeJavaScript(`document.querySelector('#petMode').checked=true;document.querySelector('#connectedMode').checked=false;changeMode()`);await sleep(1200);
    assert.equal((await getMode()).clientVisible,false);
    assert.deepEqual(await pet().webContents.executeJavaScript('sprites[0].pos'),stored);
    await request('/preferences',{snapMode:'taskbar'});await sleep(200);
    const snap=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.stopMove();s.stopThrow();s.snapAttachment=null;const a=AREAS[0];s.sendBounds(a.x+a.width/2-s.halfW,a.y+a.height-s.height-10);return {bottom:s.pos.y+s.winH,edge:a.y+a.height,attached:s.snapAttachment};})()`);
    assert.ok(snap.attached);assert.ok(snap.bottom<snap.edge);
    const gpt=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.snapAttachment=null;window.petPreferences.snapMode='gpt';const t={id:'fixture',x:toScreen(VIEW.x+100),y:toScreen(VIEW.y+100),width:toScreen(1200),height:toScreen(600)};s.setSnapTarget([t]);s.sendBounds(400,700-s.height-10);const first=s.pos.y+s.winH;s.setSnapTarget([{...t,y:t.y+toScreen(50)}]);const second=s.pos.y+s.winH;s.setSnapTarget([]);return {first,second,detached:s.snapAttachment===null};})()`);
    assert.ok(gpt.first<700&&gpt.second<750);assert.equal(gpt.second-gpt.first,50);assert.equal(gpt.detached,true);
    await settings.webContents.executeJavaScript(`document.querySelector('#disableRoaming').checked=true;document.querySelector('#disableRoaming').onchange()`);await sleep(200);
    assert.equal((await request('/preferences')).disableRoaming,true);
    const stationary=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.stopMove();s.stopThrow();const before={...s.pos};const blocked=s.tryMove()===false;s.pendingMove={};s.startMoveDrive(s.videoA);return {blocked,pending:s.pendingMove===null,stopped:s.moveRef===null,position:JSON.stringify(before)===JSON.stringify(s.pos)};})()`);
    assert.deepEqual(stationary,{blocked:true,pending:true,stopped:true,position:true});
    const manualRun=await pet().webContents.executeJavaScript(`(async()=>{
      const s=sprites[0];s.stopMove();s.stopThrow();s.snapAttachment=null;window.petPreferences.snapMode='none';
      const a=AREAS[0];s.sendBounds(a.x+a.width/2-s.halfW,a.y+a.height/2-s.halfH);const before={...s.pos};
      const group=S.buildMenuTree(s.animations)[0].children.find(g=>g.label==='跑动（实际移动）');
      s.onMenuAction(group.children.find(n=>n.label==='奔跑'));
      for(let i=0;i<100&&s.pendingMove;i++)await new Promise(r=>setTimeout(r,50));
      const manual=s.moveManual;applyPetPreferences({...window.petPreferences,disableRoaming:true});
      const preserved=s.moveManual;const el=s.front===0?s.videoA:s.videoB;
      // Seeking a software-decoded WebM can take longer than a fixed 200 ms under load.
      el.currentTime=3;
      for(let i=0;i<80&&Math.abs(s.pos.x-before.x)<=1;i++)await new Promise(r=>setTimeout(r,50));
      const moved=Math.abs(s.pos.x-before.x)>1;
      if(!moved)throw new Error('Manual run did not move: '+JSON.stringify({time:el.currentTime,duration:el.duration,paused:el.paused,seeking:el.seeking,ready:el.readyState,moveRef:s.moveRef,manual:s.moveManual,hidden:document.hidden}));
      s.stopMove();s.onMenuAction({anim:'原地左转奔跑',motion:'stationary'});
      const stationary=!s.pendingMove&&s.moveRef===null;
      return {manual,preserved,moved,stationary};
    })()`);
    assert.deepEqual(manualRun,{manual:true,preserved:true,moved:true,stationary:true});
    await settings.webContents.executeJavaScript(`document.querySelector('#disableRoaming').checked=false;document.querySelector('#disableRoaming').onchange();window.PetSettingsAutosave.flush()`);
    const menu=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.justDragged=false;s.onContextMenu({preventDefault(){},clientX:300,clientY:300});return document.querySelector('.dsh-pet-menu').textContent;})()`);
    assert.ok(menu.includes('窗口设置')&&menu.includes('碎碎念')&&menu.includes('对话'));
    await request('/preferences',{windowMode:'normal'});
    assert.ok(require('../runtime/main.js').getPetWindows().includes(pet()),'recreated pet stays registered with the window policy');
    await pet().webContents.executeJavaScript(`sprites[0].onMenuAction({action:'toggle-top'})`);await sleep(500);
    assert.equal(pet().isAlwaysOnTop(),true,JSON.stringify({mode:(await request('/preferences')).windowMode,registered:require('../runtime/main.js').getPetWindows().map(w=>w.id),pet:pet().id}));
    assert.equal((await request('/preferences')).windowMode,'top');
    await pet().webContents.executeJavaScript(`sprites[0].onMenuAction({action:'fullscreen-never'})`);await sleep(500);
    assert.equal(pet().isAlwaysOnTop(),false);
    pet().hide();getTray().emit('click');
    assert.equal(pet().isVisible(),true);assert.equal(pet().isAlwaysOnTop(),true);
    assert.equal((await request('/preferences')).windowMode,'normal','tray reveal must not change saved policy');
    assert.equal((await request('/preferences')).mode,'pet');
    assert.ok(!service.client.child);
    assert.deepEqual(errors,[]);
    const dir=path.join(__dirname,'..','qa-output');fs.mkdirSync(dir,{recursive:true});
    settings.show();settings.webContents.invalidate();await sleep(1000);
    const shot=await settings.webContents.capturePage();assert.ok(!shot.isEmpty());
    fs.writeFileSync(path.join(dir,'settings.png'),shot.toPNG());
    await settings.webContents.executeJavaScript(`document.querySelector('#pets').closest('section').scrollIntoView()`);await sleep(200);
    fs.writeFileSync(path.join(dir,'pet-size.png'),(await settings.webContents.capturePage()).toPNG());
    settings.setSize(520,760);await sleep(250);
    await settings.webContents.executeJavaScript(`document.querySelector('#pets').closest('section').scrollIntoView()`);await sleep(100);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#pets').scrollWidth<=document.querySelector('#pets').clientWidth`),true);
    fs.writeFileSync(path.join(dir,'pet-size-narrow.png'),(await settings.webContents.capturePage()).toPNG());
    await settings.webContents.executeJavaScript(`document.querySelector('#apiSection').scrollIntoView()`);await sleep(100);
    assert.equal(await settings.webContents.executeJavaScript(`document.documentElement.scrollWidth<=innerWidth`),true);
    fs.writeFileSync(path.join(dir,'api-narrow.png'),(await settings.webContents.capturePage()).toPNG());
    settings.setSize(940,760);await sleep(150);
    await settings.webContents.executeJavaScript(`document.querySelector('#apiSection').scrollIntoView()`);await sleep(100);
    assert.ok(await settings.webContents.executeJavaScript(`document.querySelector('#apiBaseUrl').getBoundingClientRect().width>600`));
    fs.writeFileSync(path.join(dir,'api-wide.png'),(await settings.webContents.capturePage()).toPNG());
    await settings.webContents.executeJavaScript(`document.querySelector('#quotaSection').scrollIntoView()`);await sleep(150);
    fs.writeFileSync(path.join(dir,'quota-layout.png'),(await settings.webContents.capturePage()).toPNG());
    console.error('VERIFY_STAGE: diagnostics-verify.cjs');
    await require('./diagnostics-verify.cjs')({settings,service,pet:pet(),dir});
    console.error('VERIFY_STAGE: task-feedback-verify.cjs');
    await require('./task-feedback-verify.cjs')({settings,service,pet:pet(),dir});
    await request('/preferences',{replyMode:'timed',replySeconds:1});
    console.error('VERIFY_STAGE: reply-verify.cjs');
    await require('./reply-verify.cjs')(pet());
    console.error('VERIFY_STAGE: whisper-verify.cjs');
    await require('./whisper-verify.cjs')({settings,service,pet:pet(),dir});
    console.error('VERIFY_STAGE: streaming-verify.cjs');
    await require('./streaming-verify.cjs')({settings,service,pet:pet()});
    console.error('VERIFY_STAGE: quota-bubble-verify.cjs');
    await require('./quota-bubble-verify.cjs')({settings,service,pet:pet(),dir});
    console.error('VERIFY_STAGE: animation-assets-verify.cjs');
    await require('./animation-assets-verify.cjs')({pet:pet(),dir});
    fs.writeFileSync(path.join(dir,'pet.png'),(await pet().webContents.capturePage()).toPNG());
    fs.writeFileSync(path.join(dir,'desktop.json'),JSON.stringify({ok:true,snap,errors},null,2));
    largeTrayMenu.show();await sleep(600);
    const trayWindow=largeTrayMenu.window;
    assert.equal(await trayWindow.webContents.executeJavaScript(`getComputedStyle(document.querySelector('button')).fontSize`),'11px');
    const traySize=await trayWindow.webContents.executeJavaScript(`({scrollHeight:document.documentElement.scrollHeight,innerHeight,lastButton:[...document.querySelectorAll('button')].at(-1).getBoundingClientRect().bottom})`);
    assert.ok(traySize.scrollHeight<=traySize.innerHeight&&traySize.lastButton<=traySize.innerHeight,JSON.stringify({traySize,bounds:trayWindow.getBounds(),content:trayWindow.getContentBounds(),zoom:trayWindow.webContents.getZoomFactor()}));
    fs.writeFileSync(path.join(dir,'tray.png'),(await trayWindow.webContents.capturePage()).toPNG());
    largeTrayMenu.close();
    await request('/preferences',{mode:'connected'});await sleep(700);
    await settings.webContents.executeJavaScript(`loadPreferences().then(()=>{selectTab('gpt');window.scrollTo(0,0);})`);await sleep(150);
    fs.writeFileSync(path.join(dir,'gpt-tab.png'),(await settings.webContents.capturePage()).toPNG());
    largeTrayMenu.show();await sleep(600);
    assert.equal(await largeTrayMenu.window.webContents.executeJavaScript(`document.documentElement.scrollHeight<=innerHeight&&[...document.querySelectorAll('button')].every(e=>e.getBoundingClientRect().bottom<=innerHeight)`),true);
    fs.writeFileSync(path.join(dir,'tray-connected.png'),(await largeTrayMenu.window.webContents.capturePage()).toPNG());
    largeTrayMenu.close();
    await request('/preferences',{replyMode:'permanent'});
    await pet().webContents.executeJavaScript(`(async()=>{const s=sprites[0];s.manualPlaying=false;s.workOn=false;s.showWhisper('Persistent across mode rebuild');await s.replyWrite;})()`);
    require('../runtime/main.js').recreate();await sleep(700);
    assert.equal(await pet().webContents.executeJavaScript(`sprites[0].whisperView?.[0]?.text`),'Persistent across mode rebuild');
    assert.equal(await pet().webContents.executeJavaScript('window.__dshPetDebug.configOk'),true);
    fs.writeFileSync(path.join(dir,'reply.png'),(await pet().webContents.capturePage()).toPNG());
    console.error('VERIFY_STAGE: autosave-verify.cjs');
    await require('./autosave-verify.cjs')({service,openSettings,getSettings});
    console.error('VERIFY_STAGE: window-stacking-verify.cjs');
    await require('./window-stacking-verify.cjs')();
    app.quit();
  }catch(e){console.error(e);app.exit(1);}
};
