const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {BrowserWindow,app}=require('electron');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
module.exports=async function verify({service,openSettings,getSettings,largeTrayMenu}){
  const errors=[];
  const pet=()=>BrowserWindow.getAllWindows().find(w=>w!==getSettings());
  const request=async(route,body)=>{const r=await fetch(service.base+route,{method:body?'PUT':'GET',body:body?JSON.stringify(body):undefined});return r.json();};
  try{
    service.client.start=async()=>{throw new Error('Codex must not start during independent UI test');};
    openSettings();const settings=getSettings();settings.webContents.on('console-message',(_event,_level,message)=>{if(/Uncaught/.test(message))errors.push(message);});
    await sleep(3000);
    const order=await settings.webContents.executeJavaScript(`(async()=>{const section=document.querySelector('#apiSection');await moveModule(section,-1);return modules(document.querySelector('#basicPanel')).map(e=>e.id);})()`);
    assert.deepEqual((await request('/preferences')).moduleOrder.basic,order);
    await settings.webContents.executeJavaScript(`moduleOrderLoaded=false;loadModuleOrder(${JSON.stringify({basic:[],gpt:[]})})`);
    await require('./module-sort-verify.cjs')(settings,service);
    const sizeControls=await settings.webContents.executeJavaScript(`(()=>{const slider=document.querySelector('.pet-size input[type=range]'),number=document.querySelector('.pet-size input[type=number]'),old=main.pets[0].size;slider.value=555;slider.dispatchEvent(new Event('input'));const fromSlider=Number(number.value)===555&&main.pets[0].size===555;number.value=420;number.dispatchEvent(new Event('input'));const fromNumber=Number(slider.value)===420&&main.pets[0].size===420;number.value=old;number.dispatchEvent(new Event('input'));return {fromSlider,fromNumber};})()`);
    assert.deepEqual(sizeControls,{fromSlider:true,fromNumber:true});
    assert.equal(await pet().webContents.executeJavaScript('window.__dshPetDebug.configOk'),true);
    const config=await request('/config');config.main.animationWeights.move=0;
    await request('/config',config.main);await sleep(600);
    const drag=await pet().webContents.executeJavaScript(`(async()=>{const s=sprites[0];s.stopMove();s.stopThrow();s.sendBounds(400,300);s.onPointerDown({button:0,pointerId:17,screenX:600,screenY:500,clientX:100,clientY:100});const before={...s.pos};s.onPointerMove({screenX:720,screenY:560});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const result={dx:s.pos.x-before.x,dy:s.pos.y-before.y,wantX:toLocal(120),wantY:toLocal(60),dragAnimation:s.animations.drag.includes(s.anim)};s.dragTrail=[];s.onPointerUp({screenX:720,screenY:560});s.stopThrow();s.stopMove();return result;})()`);
    assert.ok(Math.abs(drag.dx-drag.wantX)<1&&Math.abs(drag.dy-drag.wantY)<1);assert.equal(drag.dragAnimation,true);
    await settings.webContents.executeJavaScript(`(async()=>{document.querySelector('#proxyEndpoint').value='https://quota.example.test/balance';document.querySelector('#credential').value='manual';document.querySelector('#valuePath').value='data.balance';document.querySelector('#proxyKey').value='preview-private-key';await document.querySelector('#saveProxy').onclick();})()`);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#proxyKeyPreview').textContent`),'已保存密钥：preview…');
    await settings.webContents.executeJavaScript(`api('/quota/settings').then(fillQuota)`);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#proxyEndpoint').value`),'https://quota.example.test/balance');
    await settings.webContents.executeJavaScript(`document.querySelector('#proxyProfileName').value='Daily query';document.querySelector('#saveProxyProfile').onclick()`);
    assert.match(await settings.webContents.executeJavaScript(`document.querySelector('#proxyProfileSummary').textContent`),/quota.example.test.*手动密钥/);
    await settings.webContents.executeJavaScript(`document.querySelector('#clearProxy').onclick()`);
    assert.equal((await request('/quota/profiles')).length,1);
    await settings.webContents.executeJavaScript(`document.querySelector('#loadProxyProfile').onclick()`);
    assert.equal((await request('/quota/settings')).proxy.keyPreview,'preview…');
    await settings.webContents.executeJavaScript(`(async()=>{await document.querySelector('#deleteProxyProfile').onclick();await document.querySelector('#clearProxy').onclick();})()`);
    assert.equal((await request('/quota/profiles')).length,0);
    assert.equal((await request('/quota/settings')).proxy,null);
    await settings.webContents.executeJavaScript(`(async()=>{document.querySelector('#apiBaseUrl').value='https://example.test/v1';document.querySelector('#apiModel').value='fixture';document.querySelector('#apiKey').value='private-fixture-key';document.querySelector('#apiProfileName').value='Daily';await document.querySelector('#saveApiProfile').onclick();await document.querySelector('#clearApi').onclick();})()`);
    assert.equal((await request('/api/settings')).configured,false);
    assert.equal((await request('/api/profiles')).length,1);
    assert.match(await settings.webContents.executeJavaScript(`document.querySelector('#apiProfileSummary').textContent`),/example.test.*fixture/);
    await settings.webContents.executeJavaScript(`document.querySelector('#loadApiProfile').onclick()`);
    assert.equal((await request('/api/settings')).configured,true);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#apiKey').value`),'********');
    await settings.webContents.executeJavaScript(`document.querySelector('#saveApi').onclick()`);
    assert.equal(service.apiSettings.key(),'private-fixture-key');
    await settings.webContents.executeJavaScript(`(async()=>{await document.querySelector('#deleteApiProfile').onclick();await document.querySelector('#clearApi').onclick();})()`);
    assert.equal((await request('/api/profiles')).length,0);
    assert.equal((await request('/api/settings')).baseUrl,'');
    await sleep(900);
    const stored=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.stopMove();s.stopThrow();s.sendBounds(430,310);return s.pos;})()`);
    await sleep(80);
    const getMode=()=>settings.webContents.executeJavaScript(`({mode:currentMode,clientVisible:!document.querySelector('#gptTab').hidden,api:!!document.querySelector('#apiBaseUrl'),startup:!!document.querySelector('#autostart'),whisperVisible:getComputedStyle([...document.querySelectorAll('#autoWhisperPets label')].find(e=>e.textContent.includes('自动碎碎念'))).display!=='none'})`);
    assert.deepEqual(await getMode(),{mode:'pet',clientVisible:false,api:true,startup:true,whisperVisible:true});
    await settings.webContents.executeJavaScript(`document.querySelector('#connectedMode').checked=true;changeMode()`);await sleep(900);
    assert.equal((await getMode()).clientVisible,true);
    assert.equal(await settings.webContents.executeJavaScript(`currentTab==='gpt'&&!document.querySelector('#gptPanel').hidden&&document.querySelector('#basicPanel').hidden`),true);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#sourceDialog').open`),true);
    await settings.webContents.executeJavaScript(`document.querySelector('#chooseApiSource').onclick()`);await sleep(900);
    assert.equal((await request('/preferences')).chatSource,'api');
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#sourceDialog').open`),false);
    const tabs=await settings.webContents.executeJavaScript(`(()=>{document.querySelector('#apiBaseUrl').value='https://draft.example/v1';selectTab('gpt');const nested=['followClientStart','chatSource','notify','queryAccount','clientPets'].every(id=>document.querySelector('#gptPanel').contains(document.getElementById(id)));selectTab('basic');return {nested,draft:document.querySelector('#apiBaseUrl').value};})()`);
    assert.deepEqual(tabs,{nested:true,draft:'https://draft.example/v1'});
    assert.deepEqual(await pet().webContents.executeJavaScript('sprites[0].pos'),stored);
    await settings.webContents.executeJavaScript(`document.querySelector('#petMode').checked=true;document.querySelector('#connectedMode').checked=false;changeMode()`);await sleep(1200);
    assert.equal((await getMode()).clientVisible,false);
    assert.deepEqual(await pet().webContents.executeJavaScript('sprites[0].pos'),stored);
    await request('/preferences',{snapMode:'taskbar'});await sleep(200);
    const snap=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.stopMove();s.stopThrow();s.snapAttachment=null;const a=AREAS[0];s.sendBounds(a.x+a.width/2-s.halfW,a.y+a.height-s.height-10);return {bottom:s.pos.y+s.winH,edge:a.y+a.height,attached:s.snapAttachment};})()`);
    assert.ok(snap.attached);assert.ok(snap.bottom<snap.edge);
    const gpt=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.snapAttachment=null;window.petPreferences.snapMode='gpt';const t={id:'fixture',x:toScreen(VIEW.x+100),y:toScreen(VIEW.y+100),width:toScreen(1200),height:toScreen(600)};s.setSnapTarget([t]);s.sendBounds(400,700-s.height-10);const first=s.pos.y+s.winH;s.setSnapTarget([{...t,y:t.y+toScreen(50)}]);const second=s.pos.y+s.winH;s.setSnapTarget([]);return {first,second,detached:s.snapAttachment===null};})()`);
    assert.ok(gpt.first<700&&gpt.second<750);assert.equal(gpt.second-gpt.first,50);assert.equal(gpt.detached,true);
    await settings.webContents.executeJavaScript(`document.querySelector('#disableRoaming').checked=true;document.querySelector('#disableRoaming').onchange()`);await sleep(200);
    assert.equal((await request('/preferences')).disableRoaming,true);
    const stationary=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.stopMove();s.stopThrow();const before={...s.pos};const blocked=s.tryMove()===false;s.pendingMove={};s.startMoveDrive(s.videoA);return {blocked,pending:s.pendingMove===null,stopped:s.moveRef===null,position:JSON.stringify(before)===JSON.stringify(s.pos)};})()`);
    assert.deepEqual(stationary,{blocked:true,pending:true,stopped:true,position:true});
    await settings.webContents.executeJavaScript(`document.querySelector('#disableRoaming').checked=false;document.querySelector('#disableRoaming').onchange()`);
    const menu=await pet().webContents.executeJavaScript(`(()=>{const s=sprites[0];s.justDragged=false;s.onContextMenu({preventDefault(){},clientX:300,clientY:300});return document.querySelector('.dsh-pet-menu').textContent;})()`);
    assert.ok(menu.includes('窗口设置')&&menu.includes('碎碎念')&&menu.includes('对话'));
    const top=(await request('/preferences')).alwaysOnTop;
    await pet().webContents.executeJavaScript(`sprites[0].onMenuAction({action:'toggle-top'})`);await sleep(500);
    assert.equal(pet().isAlwaysOnTop(),!top);
    assert.equal((await request('/preferences')).mode,'pet');
    assert.ok(!service.client.child);
    assert.deepEqual(errors,[]);
    const dir=path.join(__dirname,'..','qa-output');fs.mkdirSync(dir,{recursive:true});
    settings.show();settings.webContents.invalidate();await sleep(1000);
    const shot=await settings.webContents.capturePage();assert.ok(!shot.isEmpty());
    fs.writeFileSync(path.join(dir,'settings.png'),shot.toPNG());
    await settings.webContents.executeJavaScript(`document.querySelector('#pets').closest('section').scrollIntoView()`);await sleep(200);
    fs.writeFileSync(path.join(dir,'pet-size.png'),(await settings.webContents.capturePage()).toPNG());
    settings.setSize(520,760);await sleep(250);
    await settings.webContents.executeJavaScript(`document.querySelector('#pets').closest('section').scrollIntoView()`);await sleep(100);
    assert.equal(await settings.webContents.executeJavaScript(`document.querySelector('#pets').scrollWidth<=document.querySelector('#pets').clientWidth`),true);
    fs.writeFileSync(path.join(dir,'pet-size-narrow.png'),(await settings.webContents.capturePage()).toPNG());
    await settings.webContents.executeJavaScript(`document.querySelector('#apiSection').scrollIntoView()`);await sleep(100);
    assert.equal(await settings.webContents.executeJavaScript(`document.documentElement.scrollWidth<=innerWidth`),true);
    fs.writeFileSync(path.join(dir,'api-narrow.png'),(await settings.webContents.capturePage()).toPNG());
    settings.setSize(940,760);await sleep(150);
    await settings.webContents.executeJavaScript(`document.querySelector('#apiSection').scrollIntoView()`);await sleep(100);
    assert.ok(await settings.webContents.executeJavaScript(`document.querySelector('#apiBaseUrl').getBoundingClientRect().width>600`));
    fs.writeFileSync(path.join(dir,'api-wide.png'),(await settings.webContents.capturePage()).toPNG());
    await settings.webContents.executeJavaScript(`document.querySelector('#quotaSection').scrollIntoView()`);await sleep(150);
    fs.writeFileSync(path.join(dir,'quota-layout.png'),(await settings.webContents.capturePage()).toPNG());
    await require('./diagnostics-verify.cjs')({settings,service,pet:pet(),dir});
    await require('./task-feedback-verify.cjs')({settings,service,pet:pet(),dir});
    await request('/preferences',{replyMode:'timed',replySeconds:1});
    await require('./reply-verify.cjs')(pet());
    await require('./whisper-verify.cjs')({settings,service,pet:pet(),dir});
    await require('./streaming-verify.cjs')({settings,service,pet:pet()});
    await require('./quota-bubble-verify.cjs')({settings,service,pet:pet(),dir});
    await require('./animation-assets-verify.cjs')({pet:pet(),dir});
    fs.writeFileSync(path.join(dir,'pet.png'),(await pet().webContents.capturePage()).toPNG());
    fs.writeFileSync(path.join(dir,'desktop.json'),JSON.stringify({ok:true,snap,errors},null,2));
    largeTrayMenu.show();await sleep(600);
    const trayWindow=largeTrayMenu.window;
    assert.equal(await trayWindow.webContents.executeJavaScript(`getComputedStyle(document.querySelector('button')).fontSize`),'11px');
    const traySize=await trayWindow.webContents.executeJavaScript(`({scrollHeight:document.documentElement.scrollHeight,innerHeight,lastButton:[...document.querySelectorAll('button')].at(-1).getBoundingClientRect().bottom})`);
    assert.ok(traySize.scrollHeight<=traySize.innerHeight&&traySize.lastButton<=traySize.innerHeight,JSON.stringify({traySize,bounds:trayWindow.getBounds(),content:trayWindow.getContentBounds(),zoom:trayWindow.webContents.getZoomFactor()}));
    fs.writeFileSync(path.join(dir,'tray.png'),(await trayWindow.webContents.capturePage()).toPNG());
    largeTrayMenu.close();
    await request('/preferences',{mode:'connected'});await sleep(700);
    await settings.webContents.executeJavaScript(`loadPreferences().then(()=>{selectTab('gpt');window.scrollTo(0,0);})`);await sleep(150);
    fs.writeFileSync(path.join(dir,'gpt-tab.png'),(await settings.webContents.capturePage()).toPNG());
    largeTrayMenu.show();await sleep(600);
    assert.equal(await largeTrayMenu.window.webContents.executeJavaScript(`document.documentElement.scrollHeight<=innerHeight&&[...document.querySelectorAll('button')].every(e=>e.getBoundingClientRect().bottom<=innerHeight)`),true);
    fs.writeFileSync(path.join(dir,'tray-connected.png'),(await largeTrayMenu.window.webContents.capturePage()).toPNG());
    largeTrayMenu.close();
    await request('/preferences',{replyMode:'permanent'});
    await pet().webContents.executeJavaScript(`(async()=>{const s=sprites[0];s.manualPlaying=false;s.workOn=false;s.showWhisper('Persistent across mode rebuild');await s.replyWrite;})()`);
    require('../runtime/main.js').recreate();await sleep(700);
    assert.equal(await pet().webContents.executeJavaScript(`sprites[0].whisperView?.[0]?.text`),'Persistent across mode rebuild');
    assert.equal(await pet().webContents.executeJavaScript('window.__dshPetDebug.configOk'),true);
    fs.writeFileSync(path.join(dir,'reply.png'),(await pet().webContents.capturePage()).toPNG());
    await require('./autosave-verify.cjs')({service,openSettings,getSettings});
    app.quit();
  }catch(e){console.error(e);app.exit(1);}
};
