const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async({settings,service,pet,dir})=>{
  const ui=source=>settings.webContents.executeJavaScript(source);
  await ui(`fillApiProfiles([{id:'a',name:'Daily',baseUrl:'https://api.example.test/v1',model:'chat-model'},{id:'b',name:'Second',baseUrl:'https://second.example.test/v1',model:'other-model'}]);document.querySelector('#apiProfiles').value='b';document.querySelector('#apiProfiles').onchange();`);
  assert.match(await ui(`document.querySelector('#apiProfileSummary').textContent`),/second.example.test.*other-model/);
  await ui(`document.querySelector('#apiProfileSummary').scrollIntoView({block:'center'})`);
  await new Promise(r=>setTimeout(r,200));
  fs.writeFileSync(path.join(dir,'api-profile-summary.png'),(await settings.webContents.capturePage()).toPNG());
  await ui(`fillProxyProfiles([{id:'p',name:'Daily quota',endpoint:'https://quota.example.test/balance',credential:'manual',adapter:'json',format:'remaining',valuePath:'data.balance',unit:'USD',serviceName:'My API'}]);document.querySelector('#proxyProfileSummary').scrollIntoView({block:'center'});`);
  assert.match(await ui(`document.querySelector('#proxyProfileSummary').textContent`),/quota.example.test.*手动密钥.*data.balance/);
  await new Promise(r=>setTimeout(r,200));
  fs.writeFileSync(path.join(dir,'quota-profile-summary.png'),(await settings.webContents.capturePage()).toPNG());
  service.diagnostics.record('chat-api',require('../diagnostics.cjs').issue('model-not-found',404));
  await ui(`refreshLogs().then(()=>document.querySelector('#viewErrorLogs').onclick())`);
  assert.equal(await ui(`document.querySelector('#errorBanner').hidden`),false);
  assert.match(await ui(`document.querySelector('#logEntries').textContent`),/找不到模型/);
  assert.ok(await ui(`document.querySelector('#basicPanel').contains(document.querySelector('#diagnosticsSection'))`));
  await new Promise(r=>setTimeout(r,200));
  fs.writeFileSync(path.join(dir,'diagnostics.png'),(await settings.webContents.capturePage()).toPNG());
  settings.setSize(520,760);await new Promise(r=>setTimeout(r,200));
  await ui(`document.querySelector('#diagnosticsSection').scrollIntoView()`);
  assert.equal(await ui(`document.documentElement.scrollWidth<=innerWidth`),true);
  await new Promise(r=>setTimeout(r,200));
  fs.writeFileSync(path.join(dir,'diagnostics-narrow.png'),(await settings.webContents.capturePage()).toPNG());
  settings.setSize(940,760);
  const priority=await pet.webContents.executeJavaScript(`(()=>{
    const s=sprites[0];s.manualPlaying=false;s.stopMove();s.stopThrow();s.explicitQuota=false;s.workOn=false;window.petPreferences.replyMode='permanent';
    s.showWhisper('Retained reply');s.showErrorNotice('找不到模型。请在设置中查看日志。');
    const error=s.bubble.textContent.includes('找不到模型'),retained=s.whisperView[0].text==='Retained reply';
    s.workOn=true;s.workText='Working task';s.renderBubble();const task=s.bubble.textContent.includes('Working task')&&!s.bubble.textContent.includes('找不到模型');
    s.workOn=false;s.errorNotice='';clearTimeout(s.errorNoticeTimer);s.renderBubble();const restored=s.bubble.textContent.includes('Retained reply');s.closeReply();
    return {error,retained,task,restored};
  })()`);
  assert.deepEqual(priority,{error:true,retained:true,task:true,restored:true});
  await ui(`document.querySelector('#clearLogs').onclick()`);
  assert.equal(service.diagnostics.summary().count,0);assert.equal(await ui(`document.querySelector('#errorBanner').hidden`),true);
  await ui(`fillApiProfiles([]);fillProxyProfiles([])`);
  assert.match(await ui(`document.querySelector('#apiProfileSummary').textContent`),/尚无/);
};
